
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.io.File;
import java.util.Scanner;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.*;

import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swingViewer.ViewPanel;

/*view*/
import org.graphstream.ui.view.Viewer;
//import org.graphstream.ui.view.View;
import org.graphstream.algorithm.Prim;
//import org.graphstream.algorithm.generator.DorogovtsevMendesGenerator;
/**/
import java.awt.*;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.graphstream.algorithm.BetweennessCentrality;
//import javax.swing.*;
//import javax.swing.border.*;
//import org.graphstream.algorithm.generator.BarabasiAlbertGenerator;
//import org.graphstream.graph.*;
//import org.graphstream.graph.implementations.*;
//import org.graphstream.ui.swingViewer.*;
//import org.graphstream.ui.view.*;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        admNews hilo1 = new admNews(lbl_showNewsStart, "hello", jp_newStart);
        hilo1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Graph = new javax.swing.JDialog();
        jp_show = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jc_here = new javax.swing.JComboBox<>();
        jc_there = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_recorrido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_articulation = new javax.swing.JTextArea();
        jc_diagnostic = new javax.swing.JComboBox<>();
        jp_showNews = new javax.swing.JPanel();
        lbl_showNews = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jd_CreateNewRute = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jc_newhere = new javax.swing.JComboBox<>();
        jc_newthere = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_newnode = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jp_newStart = new javax.swing.JPanel();
        lbl_showNewsStart = new javax.swing.JLabel();

        jd_Graph.setTitle("Rutas");
        jd_Graph.setBackground(new java.awt.Color(0, 0, 0));
        jd_Graph.setBounds(new java.awt.Rectangle(0, 0, 100000, 100000));
        jd_Graph.setLocation(new java.awt.Point(0, 0));
        jd_Graph.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_show.setBackground(new java.awt.Color(0, 0, 0));
        jp_show.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jp_show.setPreferredSize(new java.awt.Dimension(800, 750));

        javax.swing.GroupLayout jp_showLayout = new javax.swing.GroupLayout(jp_show);
        jp_show.setLayout(jp_showLayout);
        jp_showLayout.setHorizontalGroup(
            jp_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jp_showLayout.setVerticalGroup(
            jp_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jd_Graph.getContentPane().add(jp_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 11, -1, -1));

        jLabel1.setText("Locacon");

        jc_here.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_hereItemStateChanged(evt);
            }
        });
        jc_here.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_hereActionPerformed(evt);
            }
        });

        jc_there.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_thereItemStateChanged(evt);
            }
        });

        jLabel2.setText("Destino");

        jLabel3.setText("tiempo estimado:");

        lbl_time.setText("N/A");

        btn_iniciar.setText("Iniciar Recorrido");
        btn_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lbl_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btn_iniciar)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jc_there, 0, 246, Short.MAX_VALUE)
                    .addComponent(jc_here, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_here, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_there, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_time))
                .addGap(38, 38, 38)
                .addComponent(btn_iniciar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Particular", jPanel3);

        btn_recorrido.setText("iniciar Diagnostico");
        btn_recorrido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_recorridoMouseClicked(evt);
            }
        });
        btn_recorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recorridoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);

        txta_articulation.setColumns(20);
        txta_articulation.setRows(5);
        txta_articulation.setEnabled(false);
        jScrollPane1.setViewportView(txta_articulation);

        jc_diagnostic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calles que pueden dejar incomunicada la ciudad", "calles cerradas el dia de hoy", "camino mas corto por toda la ciudad", "Comparacion Cerrados-Cortaron acceso" }));
        jc_diagnostic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jc_diagnosticItemStateChanged(evt);
            }
        });
        jc_diagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_diagnosticActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jc_diagnostic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_recorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_recorrido)
                .addGap(18, 18, 18)
                .addComponent(jc_diagnostic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("General", jPanel4);

        jd_Graph.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 33, 380, -1));

        jp_showNews.setBackground(new java.awt.Color(0, 204, 204));
        jp_showNews.setPreferredSize(new java.awt.Dimension(162, 162));

        lbl_showNews.setForeground(new java.awt.Color(0, 153, 51));
        lbl_showNews.setText("jLabel7");

        javax.swing.GroupLayout jp_showNewsLayout = new javax.swing.GroupLayout(jp_showNews);
        jp_showNews.setLayout(jp_showNewsLayout);
        jp_showNewsLayout.setHorizontalGroup(
            jp_showNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_showNewsLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lbl_showNews)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jp_showNewsLayout.setVerticalGroup(
            jp_showNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_showNewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_showNews)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jd_Graph.getContentPane().add(jp_showNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 370, 200));

        jMenu2.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");

        jMenuItem2.setText("Crear Ruta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jd_Graph.setJMenuBar(jMenuBar1);

        jLabel4.setText("Desde");

        jLabel5.setText("Hasta");

        jButton4.setText("crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jc_newhere, 0, 217, Short.MAX_VALUE)
                    .addComponent(jc_newthere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jc_newhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_newthere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addComponent(jButton4)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Arista", jPanel1);

        jLabel6.setText("Crear Nodo");

        jButton5.setText("Crear");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(txt_newnode, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton5)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_newnode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Nodo", jPanel2);

        javax.swing.GroupLayout jd_CreateNewRuteLayout = new javax.swing.GroupLayout(jd_CreateNewRute.getContentPane());
        jd_CreateNewRute.getContentPane().setLayout(jd_CreateNewRuteLayout);
        jd_CreateNewRuteLayout.setHorizontalGroup(
            jd_CreateNewRuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreateNewRuteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jd_CreateNewRuteLayout.setVerticalGroup(
            jd_CreateNewRuteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreateNewRuteLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Empezar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 401, 153, -1));

        jp_newStart.setBackground(new java.awt.Color(0, 204, 204));

        lbl_showNewsStart.setText("jLabel7");

        javax.swing.GroupLayout jp_newStartLayout = new javax.swing.GroupLayout(jp_newStart);
        jp_newStart.setLayout(jp_newStartLayout);
        jp_newStartLayout.setHorizontalGroup(
            jp_newStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_newStartLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lbl_showNewsStart)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jp_newStartLayout.setVerticalGroup(
            jp_newStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_newStartLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lbl_showNewsStart)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        getContentPane().add(jp_newStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        jd_Graph.pack();
        jd_Graph.setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
        jd_Graph.show(true);


    }//GEN-LAST:event_jButton1MouseClicked

    private void jc_hereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_hereActionPerformed

    }//GEN-LAST:event_jc_hereActionPerformed

    private void jc_hereItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_hereItemStateChanged
        SetDefault();
        graph.getNode(jc_here.getSelectedItem().toString()).setAttribute("ui.class", "marked");
        graph.getNode(jc_there.getSelectedItem().toString()).setAttribute("ui.class", "marked");
    }//GEN-LAST:event_jc_hereItemStateChanged

    private void jc_thereItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_thereItemStateChanged
        SetDefault();
        graph.getNode(jc_here.getSelectedItem().toString()).setAttribute("ui.class", "marked");
        graph.getNode(jc_there.getSelectedItem().toString()).setAttribute("ui.class", "marked");
    }//GEN-LAST:event_jc_thereItemStateChanged

    private void btn_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseClicked
        Dikstra(jc_here.getSelectedItem().toString(), jc_there.getSelectedItem().toString());
    }//GEN-LAST:event_btn_iniciarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (graph.getNode(jc_newhere.getSelectedItem().toString()) != null && graph.getNode(jc_newhere.getSelectedItem().toString()) != null) {
            Random ran = new Random();
            Node nodexTo = graph.getNode(jc_newhere.getSelectedItem().toString());
            Node nodexFrom = graph.getNode(jc_newthere.getSelectedItem().toString());
            String name = nodexTo.getId() + nodexFrom.getId();
            String name2 = nodexFrom.getId() + nodexTo.getId();
            if (graph.getEdge(name) == null && graph.getEdge(name2) == null && nodexTo != nodexFrom) {
                graph.addEdge(name, nodexTo, nodexFrom).addAttribute("length", ran.nextInt(15) + 1);
                LoadCombo();
                SetDefault();
                JOptionPane.showMessageDialog(null, "Ruta Creada Exitosamente", "Ruta Creada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "La ruta deseada ya existe, o hace referencia a si misma", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        graph.addNode(txt_newnode.getText());
        graph.getNode(txt_newnode.getText()).setAttribute("estate", false);
        LoadCombo();
        SetDefault();
        txt_newnode.setText("");


    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jp_show.removeAll();
        starGraph();
        display();
        btn_iniciar.show(true);
        btn_recorrido.show(true);
        ArrayList<Node> closed = CrashGenerated(false);
        String closed01 = "";
        for (int i = 0; i < closed.size(); i++) {
            closed01 += closed.get(i).getId() + "<br>";
        }
        String Datos = "<html><body>Las calle cerradas son:  varias <br>" + closed01 + "</body></html>";
        admNews hilo1 = new admNews(lbl_showNews, Datos, jp_showNews);
        hilo1.start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btn_iniciar.show(false);
        btn_recorrido.show(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jd_CreateNewRute.show();
        jd_CreateNewRute.pack();
        jd_CreateNewRute.setLocationRelativeTo(jd_Graph);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_recorridoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_recorridoMouseClicked
        try {
            Prim();
            DFS();
            Articulation(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_recorridoMouseClicked

    private void btn_recorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recorridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_recorridoActionPerformed

    private void jc_diagnosticItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jc_diagnosticItemStateChanged

    }//GEN-LAST:event_jc_diagnosticItemStateChanged

    private void jc_diagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_diagnosticActionPerformed
        if (jc_diagnostic.getSelectedIndex() == 0) {
            ArrayList<Node> articulation = Articulation(true);
            SetDefault();
            for (Node node : articulation) {
                node.setAttribute("ui.class", "marked_articulation");
            }
        } else if (jc_diagnostic.getSelectedIndex() == 1) {
            CrashGenerated(true);
            SetDefault();

        } else if (jc_diagnostic.getSelectedIndex() == 3) {
            Comparative(Articulation(false), CrashGenerated(false));
            
        } else {
            txta_articulation.setText("");
            Prim();
            try {
                DFS();
            } catch (InterruptedException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jc_diagnosticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });

    }

    public void starGraph() {
        graph = CreateGraph(ReadFile());
        LoadCombo();
        GenerateCrash();
        SetDefault();

        graph.addAttribute("ui.stylesheet", styleSheet);

        jp_show.repaint();

    }

    private void display() {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JPanel panel = new JPanel(new GridLayout()) {
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(800, 650);
            }
        };
        panel.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = viewer.addDefaultView(false);
        panel.add(viewPanel);
        frame.add(panel);
        frame.pack();
        jp_show.add(viewPanel);

    }

    public File ReadFile() {
        JFileChooser fileChooseer = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Archivos", "txt", "csv", "docx");
        fileChooseer.addChoosableFileFilter(filter);
        int op = fileChooseer.showOpenDialog(this);
        String extension = fileChooseer.getSelectedFile().getPath();
        if (op == JFileChooser.APPROVE_OPTION) {
            return fileChooseer.getSelectedFile();
        }
        return null;
    }

    public void LoadCombo() {
        DefaultComboBoxModel modelHere = new DefaultComboBoxModel();
        DefaultComboBoxModel modelThere = new DefaultComboBoxModel();
        DefaultComboBoxModel modelNewThere = new DefaultComboBoxModel();
        DefaultComboBoxModel modelNewHere = new DefaultComboBoxModel();
        for (Node node : graph) {
            modelHere.addElement(node);
            modelThere.addElement(node);
            modelNewThere.addElement(node);
            modelNewHere.addElement(node);
        }
        jc_here.setModel(modelHere);
        jc_there.setModel(modelThere);
        jc_newhere.setModel(modelNewHere);
        jc_newthere.setModel(modelNewThere);
    }

    public Graph CreateGraph(File toCreate) {
        Graph graph = new SingleGraph("Principal Graph");
        graph.setNullAttributesAreErrors(true);//para evitar elementos en nulo 
        graph.setStrict(false);
        graph.setAutoCreate(true);
        BetweennessCentrality bcb = new BetweennessCentrality();
        bcb.setWeightAttributeName("weight");

        if (toCreate.exists()) {
            Scanner sc = null;
            try {
                sc = new Scanner(toCreate);
                while (sc.hasNext()) {

                    String data[] = sc.next().split(",");
                    for (int i = 0; i < 3; i++) {//el largo deberia ser 3 

                        if (i == 2) {

                            if (!(graph.getEdge(data[2]) != null)) {
                                Random ran = new Random();
                                int weigth = ran.nextInt(15) + 1;
                                graph.addEdge(data[2], data[0], data[1]).addAttribute("length", weigth);
                                graph.getNode(data[0]).setAttribute("estate", false);
                                graph.getNode(data[1]).setAttribute("estate", false);
                                Node nodea = graph.getNode(data[0]);
                                Node nodeb = graph.getNode(data[1]);
                                bcb.setWeight(nodea, nodeb, weigth);
                            }
                        }
                    }
                }
            } catch (Exception e) {
            }
            sc.close();
        }//Fin del if 
        bcb.init(graph);
        bcb.compute();

        return graph;
    }

    public void GenerateCrash() {
        Random ranCrash = new Random();
        Random ranLucky = new Random();
        int lucky = ranLucky.nextInt((graph.getEdgeCount() / 2)) + 1;
        for (int i = 0; i < lucky; i++) {
            int crash = ranCrash.nextInt(graph.getEdgeCount() - 2);
            graph.getNode(crash).setAttribute("ui.class", "marked_closed");
            graph.getNode(crash).setAttribute("estate", true);
        }
    }

    ArrayList<Node> CrashGenerated(boolean showText) {
        ArrayList<Node> closed = new ArrayList();
        String isClosed = "";
        for (int i = 0; i < graph.getNodeCount(); i++) {

            if ((boolean) graph.getNode(i).getAttribute("estate")) {
                isClosed += "\n" + graph.getNode(i).getId();
                closed.add(graph.getNode(i));
            }
        }
        if (showText) {
            txta_articulation.setText(isClosed);
        }
        return closed;
    }

    public void Dikstra(String from, String to) {
        admHilo hilo1 = new admHilo(lbl_time, jc_here, jc_there, btn_iniciar, graph);
        hilo1.Dikstra(from, to);
        hilo1.start();
        graph.getNode(jc_here.getSelectedItem().toString()).setAttribute("ui.class", "marked");
        graph.getNode(jc_there.getSelectedItem().toString()).setAttribute("ui.class", "marked");

    }

    public void DFS() throws InterruptedException {
        int level = 0;
        DepthFirstIterator it = new DepthFirstIterator(graph.getNode(jc_here.getSelectedItem().toString()));
        graph.getNode(0).setAttribute("level", level);
        while (it.hasNext()) {
            Node n = it.next();
            level += 1;
            n.setAttribute("level", level);
            n.addAttribute("ui.label", n.getId());
        }
    }

    public void Prim() {
        /*  for (Edge edge : graph.getEachEdge()) {
            edge.addAttribute("weight", (Object) edge.getAttribute("length"));
        }*/
        Prim prim = new Prim("ui.class", "intree", "notintree");
        prim.init(graph);
        prim.compute();
    }

    public void SetDefault() {
        for (Node node : graph) {
            if (!((boolean) node.getAttribute("estate"))) {
                node.setAttribute("ui.class", "marked_defult");
            } else {
                node.setAttribute("ui.class", "marked_closed");
            }
        }
        for (Edge edge : graph.getEachEdge()) {
            edge.addAttribute("ui.class", "highlight_black");
        }
        for (Node node : graph) {//Agrega las etiquetas
            node.addAttribute("ui.label", node.getId());
        }
        for (Edge edge : graph.getEachEdge()) {
            edge.addAttribute("ui.label", (Object) edge.getAttribute("length"));
        }

    }

    ArrayList<Node> Articulation(boolean showText) {
        ArrayList<Node> articulations = new ArrayList();
        String dangerIfIsClosed = "";
        for (int i = 0; i < graph.getNodeCount(); i++) {
            if ((Double) graph.getNode(i).getAttribute("Cb") > 2.0) {
                dangerIfIsClosed += "\n" + graph.getNode(i).getId();
                articulations.add(graph.getNode(i));
            }
        }
        if (showText) {
            txta_articulation.setText(dangerIfIsClosed);
        }
        return articulations;
    }

    public void Comparative(ArrayList<Node> articulations, ArrayList<Node> closed) {
        String noAcces = "";
        for (Node node : closed) {
            if (articulations.contains(node)) {
                noAcces += "\n" + node.getId();
            }
        }
        if (noAcces.length() > 0) {
            noAcces += "\n\n NO HAY ACCESO A CIERTAS PARTES DE LA CIUDAD HOY";
            txta_articulation.setText(noAcces);
        } else {
            noAcces += "\n\n Ninguna calle importante esta cerrrada hoy";
            txta_articulation.setText(noAcces);
        }
    }
    Graph graph;
    protected String styleSheet
            = "node {"
            + "	fill-color: blue;"
            + "text-size: 15px;"
            + "}"
            + "node.marked {"
            + "	fill-color: green;"
            + "text-color: green;"
            + "shape: box;"
            + "text-size: 20px;"
            + "}"
            + "node.marked_defult {"
            + "fill-color: blue;"
            + "text-color: black;"
            + "text-size: 15px;"
            + "}"
            + "node.marked_visited{"
            + "	fill-color: yellow;"
            + "text-size: 10.5px;"
            + "}"
            + "node.marked_closed{"
            + "fill-color: red;"
            + "text-color: black;"
            + "text-size: 15px;"
            + "}"
            + "node.marked_articulation{"
            + "	fill-color: orange;"
            + "text-size: 15px;"
            + "}"
            + "graph {\n"
            + " fill-color: gray;\n"
            + "fill-mode: plain;"
            + "}"
            + "edge.highlight {  "
            + "fill-color: rgb(200,39,65);\n"
            + "text-color: black;"
            + "text-size: 15px;"
            + "size: 3px;"
            + "}"
            + "edge.highlight_black {  "
            + " fill-color: black;\n"
            + "text-color: black;"
            + "text-size: 15px;"
            + "   size: 3px;"
            + "}"
            + "edge.highlight1 {  "
            + "   fill-color: green;\n"
            + "text-color: black;"
            + "text-size: 15px;"
            + "   size: 3px;"
            + "}"
            + "edge.highlightalter {  "
            + "   fill-color: yellow;\n"
            + "   size: 3px;"
            + "}"
            + "edge .notintree {"
            + "size:1px;fill-color:black;"
            + "} "
            + "edge .intree {"
            + "size:3px;"
            + "fill-color:orange;"
            + "}"
            + "node.hide {"
            + "	fill-color: gray;"
            + "text-size: 0px;"
            + "}"
            + "edge.hide {"
            + "	fill-color: gray;"
            + "text-size: 0px;"
            + "}";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_recorrido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> jc_diagnostic;
    private javax.swing.JComboBox<String> jc_here;
    private javax.swing.JComboBox<String> jc_newhere;
    private javax.swing.JComboBox<String> jc_newthere;
    private javax.swing.JComboBox<String> jc_there;
    private javax.swing.JDialog jd_CreateNewRute;
    private javax.swing.JDialog jd_Graph;
    private javax.swing.JPanel jp_newStart;
    private javax.swing.JPanel jp_show;
    private javax.swing.JPanel jp_showNews;
    private javax.swing.JLabel lbl_showNews;
    private javax.swing.JLabel lbl_showNewsStart;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTextField txt_newnode;
    private javax.swing.JTextArea txta_articulation;
    // End of variables declaration//GEN-END:variables
}
